# Generated by Django 2.2.28 on 2022-04-21 08:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images'),
            preserve_default=False,
        ),
    ]
