# Generated by Django 2.2.28 on 2022-04-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_advertise_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
